### ISSUE TITLE
Ruby dependency indication

### ISSUE THREAD

**Issue by andreyorst** [jbomanson/buffer-by-name.kak#1]
I've installed your plugin and it wasn't working because it needs ruby, and I have no in my system. I've searched through readme and did not seen ruby requirements. Of course I could look into language section, but this is not the best solution I think

**Comment by jbomanson** [comment]
Apologies about the hidden dependency and thanks for opening an issue.

I added a note on the ruby dependency in the README and updated the plugin to alert the user if ruby is not found.
